version: '3.9'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/

  api:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/opt/app
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=example
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017


volumes:
  db_data:
