FROM python:3.11

ENV PYTHONUNBUFFERED 1

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY requirements/requirements.txt /opt/app/
COPY requirements/requirements.dev.txt /opt/app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt --no-cache-dir
RUN pip install -r requirements.dev.txt --no-cache-dir

COPY /src /opt/app/

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--reload"]
