---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm api sh -c "pytest"
      - name: Lint
        run: docker-compose run --rm api sh -c "flake8"
